spring:
  application:
    name: GameOfLife
  profiles:
    active: @spring.profiles.active@
server:
  error:
    include-message: always
  port: ${PORT:8080}
allowed-origin: ${ALLOWED_ORIGIN:http://localhost:5173}